export const labStaticViewModel = {
  header: {
    title: '动力室',
  },
  rankPanel: {
    eyebrow: '航行头衔',
    stagePrefix: '第',
    stageSuffix: '阶段',
    todayLabel: '今日动能',
    totalLabel: '动力储备',
    targetLabel: '晋升目标',
    maxLabel: '已抵达懒兽巅峰',
  },
  sections: {
    tasks: {
      title: '动力维护日志',
      subtitle: '航次每日更新',
      progressLabel: '维护进度',
      rewardSuffix: ' 动力',
      doneText: '检修完毕',
    },
    achievements: {
      title: '大航海成就',
      rewardPrefix: '+',
    },
  },
  ranks: [
    {
      level: 1,
      name: '海滩漫步者',
      exp: 0,
      iconName: 'shell',
      tone: 'slate',
      theme: 'basic',
      iconColor: '#94a3b8',
      cardIconColor: '#94a3b8',
    },
    {
      level: 2,
      name: '浅滩摸鱼手',
      exp: 50,
      iconName: 'waves',
      tone: 'cyan',
      theme: 'basic',
      iconColor: '#0891b2',
      cardIconColor: '#0891b2',
    },
    {
      level: 3,
      name: '茶歇守卫官',
      exp: 120,
      iconName: 'coffee',
      tone: 'orange',
      theme: 'basic',
      iconColor: '#ea580c',
      cardIconColor: '#ea580c',
    },
    {
      level: 4,
      name: '划水见习生',
      exp: 200,
      iconName: 'wind',
      tone: 'emerald',
      theme: 'mid',
      iconColor: '#ffffff',
      cardIconColor: '#ffffff',
    },
    {
      level: 5,
      name: '资深舵手',
      exp: 350,
      iconName: 'compass',
      tone: 'blue',
      theme: 'mid',
      iconColor: '#ffffff',
      cardIconColor: '#ffffff',
    },
    {
      level: 6,
      name: '隐身巡航员',
      exp: 500,
      iconName: 'ghost',
      tone: 'indigo',
      theme: 'mid',
      iconColor: '#e2e8f0',
      cardIconColor: '#ffffff',
    },
    {
      level: 7,
      name: '风暴避难者',
      exp: 750,
      iconName: 'anchor',
      tone: 'violet',
      theme: 'high',
      iconColor: '#ffffff',
      cardIconColor: '#ffffff',
    },
    {
      level: 8,
      name: '极速快艇王',
      exp: 1000,
      iconName: 'zap',
      tone: 'rose',
      theme: 'high',
      iconColor: '#ffffff',
      cardIconColor: '#ffffff',
    },
    {
      level: 9,
      name: '深海霸主',
      exp: 1500,
      iconName: 'ship',
      tone: 'blue',
      theme: 'high',
      iconColor: '#ffffff',
      cardIconColor: '#ffffff',
    },
    {
      level: 10,
      name: '懒兽至尊',
      exp: 2000,
      iconName: 'crown',
      tone: 'amber',
      theme: 'ultra',
      iconColor: '#92400e',
      cardIconColor: '#92400e',
    },
  ],
  score: {
    total: 1280,
    today: 45,
    selectedRankIndex: 9,
  },
  tasks: [
    {
      id: 'water',
      title: '深海补水计划',
      desc: '摄入 250ml 水分，维持机体代谢活力',
      reward: 2,
      count: 3,
      limit: 8,
      tone: 'blue',
      iconName: 'droplets',
    },
    {
      id: 'move',
      title: '甲板体能回收',
      desc: '站立拉伸 3 分钟，缓解久坐导致的腰椎压力',
      reward: 3,
      count: 2,
      limit: 10,
      tone: 'emerald',
      iconName: 'accessibility',
    },
    {
      id: 'eye',
      title: '远眺海平线',
      desc: '凝视 5 米外目标，放松睫状肌以保护视力',
      reward: 3,
      count: 1,
      limit: 10,
      tone: 'amber',
      iconName: 'eye',
    },
    {
      id: 'leave',
      title: '准点回港靠岸',
      desc: '在法定下班时间准时离港，保障心理健康边界',
      reward: 10,
      count: 0,
      limit: 1,
      tone: 'rose',
      iconName: 'log-out',
    },
    {
      id: 'toilet',
      title: '潜艇压力排放',
      desc: '进入静谧空间独处 10 分钟，进行深层情绪减压',
      reward: 5,
      count: 1,
      limit: 5,
      tone: 'indigo',
      iconName: 'navigation',
      rotate: true,
    },
  ],
  achievements: [
    {
      id: 'discipline',
      title: '黄金航线守护者',
      desc: '连续 7 天执行准点回港，捍卫私人生活领海',
      reward: 50,
      progress: 5,
      target: 7,
    },
    {
      id: 'idle-master',
      title: '静默巡航专家',
      desc: '累计在非工位区域减压 120 分钟，达成深度平衡',
      reward: 50,
      progress: 85,
      target: 120,
      unit: '分钟',
    },
    {
      id: 'whale',
      title: '满电核动力',
      desc: '单周完成 40 次基础补水，身体机能满负荷运转',
      reward: 50,
      progress: 28,
      target: 40,
    },
  ],
} as const
