// 首页静态视图模型仅服务于阶段 1 的高保真还原。
// 正式业务逻辑会在后续阶段改由 feature model 统一承接。

export const dashboardStaticViewModel = {
  header: {
    title: '薪潮涌动',
    subtitle: '此刻，金钱正如潮水般涌来',
  },
  income: {
    label: '今日累计避风收益',
    value: '¥128.632',
    rate: '航速 0.024/s',
    rateBadge: '自动结算',
    depthLabel: '避风收益深度',
    workLabel: '工时',
    workPercent: 68,
    idlePercent: 32,
    moyuIncome: '¥46.125',
    moyuLabel: '今日入账',
    monthlyIncome: '¥6,340.632',
    monthlyLabel: '本月已赚',
  },
  timer: {
    leftTitle: '离岗倒计时',
    leftValue: '02:18:42',
    leftProgress: 78,
    stayLabel: '停留',
    rightTitle: '点击避风',
    rightActiveTitle: '避风中',
    rightValue: '01:24:16',
  },
  taskPreview: {
    sectionTitle: '今日航行目标',
    actionText: '潮汐任务',
    title: '航道任务清理',
    completed: 2,
    total: 6,
    segments: [
      { filled: true },
      { filled: true },
      { filled: false },
      { filled: false },
      { filled: false },
      { filled: false },
    ],
  },
  regularTides: {
    sectionTitle: '常规波动',
    actionText: '查看日历',
    items: [
      {
        id: 'salary',
        title: '发薪大潮',
        days: '12',
        suffix: '天后',
        tone: 'blue',
        iconType: 'wallet',
      },
      {
        id: 'weekend',
        title: '双休倒计时',
        days: '4',
        suffix: '天后',
        tone: 'emerald',
        iconType: 'calendar-days',
      },
    ],
  },
  importantDates: {
    sectionTitle: '岁月坐标',
    items: [
      {
        id: 'anniversary',
        title: '结婚纪念日',
        date: '10月20日',
        remaining: '28',
        suffix: '天后',
        tone: 'rose',
        iconType: 'heart',
      },
      {
        id: 'birthday',
        title: '我的生日',
        date: '12月05日',
        remaining: '74',
        suffix: '天后',
        tone: 'amber',
        iconType: 'gift',
      },
      {
        id: 'bonus',
        title: 'Q3 季度奖金',
        date: '09月30日',
        remaining: '8',
        suffix: '天后',
        tone: 'blue',
        iconType: 'star',
      },
    ],
  },
  lifeJourney: {
    sectionTitle: '人生航程看板',
    badgeText: 'Voyage Ledger',
    items: [
      {
        id: 'life',
        eyebrow: '生命航程 (LIFE)',
        value: '11,240',
        unit: '天',
        descriptionPrefix: '这是你从',
        descriptionHighlight: '诞生启航',
        descriptionSuffix: '至今所经历的日夜。',
      },
      {
        id: 'career',
        eyebrow: '职场航程 (CAREER)',
        value: '2,823',
        unit: '天',
        descriptionPrefix: '自步入',
        descriptionHighlight: '社会熔炉',
        descriptionSuffix: '起，你已交付出的岁月。',
      },
      {
        id: 'retire',
        eyebrow: '退役倒计时 (RETIRE)',
        value: '10,675',
        unit: '天',
        descriptionPrefix: '距离你可以',
        descriptionHighlight: '正式卸甲',
        descriptionSuffix: '，还有这些定额任务。',
        progress: 45,
      },
      {
        id: 'final',
        eyebrow: '终点倒计时 (FINAL)',
        value: '19,807',
        unit: '天',
        quote: '"警告：航线即将耗尽，此数据不可逆转。"',
        note: '* 基于预计 85 岁自然终点计算。每一秒都是该生命周期中不可再生的奢侈品。',
      },
    ],
  },
  editModal: {
    title: '修正避风时长',
    subtitle: '手动校准今日避风港停留的时间',
    cancelText: '取消',
    confirmText: '确认保存',
  },
} as const
