export const profileHomeModel = {
  user: {
    name: '摸鱼小队长',
    checkInDays: 10,
    rank: {
      level: 9,
      name: '深海霸主',
      tone: 'rose',
      iconName: 'ship',
      iconColor: '#e11d48',
    },
  },
  avatarPresets: [
    { id: 'preset-1', label: 'Felix', src: '/assets/images/profile/avatar-felix.svg' },
    { id: 'preset-2', label: 'Aneka', src: '/assets/images/profile/avatar-aneka.svg' },
    { id: 'preset-3', label: 'Jasper', src: '/assets/images/profile/avatar-jasper.svg' },
    { id: 'preset-4', label: 'Milo', src: '/assets/images/profile/avatar-milo.svg' },
    { id: 'preset-5', label: 'Luna', src: '/assets/images/profile/avatar-luna.svg' },
    { id: 'preset-6', label: 'Zoe', src: '/assets/images/profile/avatar-zoe.svg' },
  ],
  consoleItems: [
    {
      title: '基本信息设置',
      desc: '修改航行昵称、薪资基数及工时',
      tone: 'blue',
      iconName: 'user',
      iconColor: '#3b82f6',
      url: '/features/profile-settings/settings',
    },
    {
      title: '岁月坐标设置',
      desc: '管理重要的时间节点与纪念日',
      tone: 'emerald',
      iconName: 'map-pin',
      iconColor: '#10b981',
      url: '/features/time-axis/time-axis-settings',
    },
    {
      title: '查看日历',
      desc: '纵览航行周期与重要考勤节点',
      tone: 'indigo',
      iconName: 'calendar',
      iconColor: '#4f46e5',
      url: '/features/calendar/calendar',
    },
    {
      title: '任务中心设置',
      desc: '配置你的每日航行目标与奖励',
      tone: 'rose',
      iconName: 'target',
      iconColor: '#f43f5e',
      badge: '3',
      url: '/features/lab/lab',
      navMethod: 'switchTab',
    },
  ],
  aboutItems: [
    {
      title: '加入社群',
      desc: '与万千舵手交流摸鱼心得',
      tone: 'indigo',
      iconName: 'users',
      iconColor: '#6366f1',
      url: '/features/community/join',
    },
    {
      title: '关于软件',
      desc: '版本 v1.0.0 (Build 2026)',
      tone: 'slate',
      iconName: 'info',
      iconColor: '#64748b',
      url: '/features/about/about',
    },
  ],
  storageItems: [
    {
      title: '数据同步中心',
      desc: '管理本地备份、云端同步与隐私',
      tone: 'amber',
      iconName: 'database',
      iconColor: '#f59e0b',
      highlight: true,
      url: '/features/data-center/data-center',
    },
  ],
} as const
