export const reportModel = {
  trend: {
    riseText: '+12.5%',
    bars: [
      { day: '1', incomeHeight: '32%', durationHeight: '26%', incomeText: '¥24', durationText: '1.2h' },
      { day: '2', incomeHeight: '38%', durationHeight: '30%', incomeText: '¥29', durationText: '1.5h' },
      { day: '3', incomeHeight: '46%', durationHeight: '34%', incomeText: '¥35', durationText: '1.7h' },
      { day: '4', incomeHeight: '52%', durationHeight: '40%', incomeText: '¥41', durationText: '2.0h' },
      { day: '5', incomeHeight: '44%', durationHeight: '36%', incomeText: '¥34', durationText: '1.8h' },
      { day: '6', incomeHeight: '58%', durationHeight: '46%', incomeText: '¥48', durationText: '2.3h' },
      { day: '7', incomeHeight: '64%', durationHeight: '50%', incomeText: '¥53', durationText: '2.6h' },
      { day: '8', incomeHeight: '48%', durationHeight: '38%', incomeText: '¥39', durationText: '1.9h' },
      { day: '9', incomeHeight: '42%', durationHeight: '34%', incomeText: '¥32', durationText: '1.7h' },
      { day: '10', incomeHeight: '72%', durationHeight: '62%', incomeText: '¥61', durationText: '3.1h' },
      { day: '11', incomeHeight: '68%', durationHeight: '58%', incomeText: '¥58', durationText: '2.9h' },
      { day: '12', incomeHeight: '54%', durationHeight: '44%', incomeText: '¥45', durationText: '2.2h' },
      { day: '13', incomeHeight: '47%', durationHeight: '40%', incomeText: '¥37', durationText: '2.0h' },
      { day: '14', incomeHeight: '62%', durationHeight: '54%', incomeText: '¥52', durationText: '2.7h' },
      { day: '15', incomeHeight: '48%', durationHeight: '38%', incomeText: '¥40', durationText: '1.9h' },
      { day: '16', incomeHeight: '56%', durationHeight: '45%', incomeText: '¥46', durationText: '2.3h' },
      { day: '17', incomeHeight: '60%', durationHeight: '51%', incomeText: '¥49', durationText: '2.5h' },
      { day: '18', incomeHeight: '66%', durationHeight: '55%', incomeText: '¥55', durationText: '2.8h' },
      { day: '19', incomeHeight: '50%', durationHeight: '42%', incomeText: '¥42', durationText: '2.1h' },
      { day: '20', incomeHeight: '85%', durationHeight: '74%', incomeText: '¥72', durationText: '3.7h' },
      { day: '21', incomeHeight: '74%', durationHeight: '64%', incomeText: '¥64', durationText: '3.2h' },
      { day: '22', incomeHeight: '58%', durationHeight: '47%', incomeText: '¥47', durationText: '2.4h' },
      { day: '23', incomeHeight: '52%', durationHeight: '43%', incomeText: '¥44', durationText: '2.1h' },
      { day: '24', incomeHeight: '70%', durationHeight: '60%', incomeText: '¥59', durationText: '3.0h' },
      { day: '25', incomeHeight: '67%', durationHeight: '58%', incomeText: '¥56', durationText: '2.9h' },
      { day: '26', incomeHeight: '61%', durationHeight: '50%', incomeText: '¥50', durationText: '2.5h' },
      { day: '27', incomeHeight: '57%', durationHeight: '46%', incomeText: '¥46', durationText: '2.3h' },
      { day: '28', incomeHeight: '63%', durationHeight: '52%', incomeText: '¥51', durationText: '2.6h' },
      { day: '29', incomeHeight: '69%', durationHeight: '59%', incomeText: '¥57', durationText: '3.0h' },
      { day: '30', incomeHeight: '76%', durationHeight: '69%', incomeText: '¥65', durationText: '3.4h' },
    ],
    summary: {
      incomeTotal: '¥1,824',
      durationTotal: '42.5h',
    },
  },
  annualCards: [
    { title: '年度摸鱼收入', value: '¥12,480.50', tone: 'indigo', iconName: 'coins' },
    { title: '摸鱼打卡天数', value: '248 天', tone: 'amber', iconName: 'calendar-days' },
    { title: '月均摸鱼收益', value: '¥1,040.00', tone: 'blue', iconName: 'trending-up' },
    { title: '击败全国社畜', value: '98.5%', tone: 'rose', iconName: 'trophy' },
  ],
  ratio: {
    stats: {
      day: { work: 75, moyu: 25 },
      week: { work: 68, moyu: 32 },
      month: { work: 60, moyu: 40 },
      year: { work: 82, moyu: 18 },
    },
  },
  historyItems: [
    { date: '09-18', duration: '02:15:20', income: '42.5' },
    { date: '09-17', duration: '01:45:10', income: '33.2' },
    { date: '09-16', duration: '03:10:00', income: '58.8' },
    { date: '09-15', duration: '00:55:30', income: '15.4' },
    { date: '09-14', duration: '02:30:15', income: '48.0' },
  ],
} as const
