export const timeAxisStaticViewModel = {
  title: '航行档案设置',
  notebooks: [
    { id: 'all', name: '全部', iconId: 'layers', tone: 'slate' },
    { id: 'commemorative', name: '纪念日本', iconId: 'heart', tone: 'rose' },
    { id: 'travel', name: '旅游本', iconId: 'map', tone: 'amber' },
    { id: 'life', name: '人生本', iconId: 'user', tone: 'blue' },
    { id: 'career', name: '职场本', iconId: 'briefcase', tone: 'indigo' },
  ],
  entries: [
    {
      id: 'anniversary',
      title: '结婚纪念日',
      date: '2023-10-20',
      notebookId: 'commemorative',
      isAnniversary: true,
    },
    {
      id: 'travel-memory',
      title: '西藏大冒险',
      date: '2024-05-12',
      notebookId: 'travel',
      isAnniversary: false,
    },
    {
      id: 'career-milestone',
      title: '拿到高级架构师证',
      date: '2022-07-15',
      notebookId: 'career',
      isAnniversary: false,
    },
  ],
  texts: {
    addCta: '存入新档案卡片',
    emptyTitle: '档案本虚位以待',
    titleField: '档案名称',
    titlePlaceholder: '记录此刻的意义...',
    dateField: '发生日期',
    anniversaryTitle: '周年提醒模式',
    anniversarySubtitle: 'Anniversary Mode',
    notebookField: '存入档案本',
    createTitle: '新增档案卡片',
    editTitle: '编辑档案',
    confirmCreate: '确认录入',
    confirmSave: '保存修改',
    deleteLabel: '删除',
  },
  draft: {
    title: '',
    date: '',
    notebookId: 'commemorative',
    isAnniversary: true,
  },
} as const
