export const timeAxisStaticViewModel = {
  title: '岁月坐标设置',
  groups: ['全部', '职场生涯', '财富增长', '生活印记', '自定义'],
  entries: [
    {
      id: 'anniversary',
      title: '结婚纪念日',
      date: '2023-10-20',
      group: '生活印记',
      iconLabel: '爱',
      tag: '公历',
      countdown: '还有 28 天',
      tone: 'rose',
    },
    {
      id: 'bonus',
      title: '薪潮爆发日',
      date: '2026-09-30',
      group: '财富增长',
      iconLabel: '奖',
      tag: '公历',
      countdown: '剩余 8 天',
      tone: 'blue',
    },
    {
      id: 'birthday',
      title: '我的生日',
      date: '2026-12-05',
      group: '生活印记',
      iconLabel: '生',
      tag: '公历',
      countdown: '还有 74 天',
      tone: 'amber',
    },
  ],
  iconChoices: [
    { id: 'heart', label: '爱', tone: 'rose' },
    { id: 'gift', label: '礼', tone: 'amber' },
    { id: 'star', label: '星', tone: 'blue' },
    { id: 'trophy', label: '奖', tone: 'yellow' },
    { id: 'briefcase', label: '职', tone: 'indigo' },
    { id: 'rocket', label: '启', tone: 'violet' },
    { id: 'coffee', label: '生', tone: 'orange' },
    { id: 'camera', label: '记', tone: 'emerald' },
    { id: 'music', label: '趣', tone: 'pink' },
    { id: 'calendar', label: '常', tone: 'slate' },
  ],
  draft: {
    title: '',
    date: '',
    group: '职场生涯',
    isAnniversary: true,
    iconId: 'star',
  },
} as const
